Update addFlight methods in android and ios
cartrawler/mobility-sdk-docs pull request #27
Opened 2021-07-21 14:04 UTC by humphriest

2021-07-21 15:05 UTC, gianpaj requested changes
Just a wording suggestions on the `direction` param

2021-07-21 15:05 UTC, gianpaj commented on Android.md
> +`<direction>` is an **enum** with the values of either `DeeplinkDirection.DROPOFF_TO_ORIGIN` or `DeeplinkDirection.PICKUP_FROM_DESTINATION`. `DeeplinkDirection.DROPOFF_TO_ORIGIN` is used when the use
```suggestion
`<direction>` is an **enum** with the values of either `DeeplinkDirection.DROPOFF_TO_ORIGIN` or `DeeplinkDirection.PICKUP_FROM_DESTINATION`.
`DeeplinkDirection.DROPOFF_TO_ORIGIN` is used when the user on the transport (taxi, etc.) is to be dropped off at the airport they are flying out of, using the flight details provided.
`DeeplinkDirection.PICKUP_FROM_DESTINATION` is used when the user on the transport (taxi, etc.) is to be picked up at the airport they are landing at, using the flight details provided.
```

or 

`DeeplinkDirection.DROPOFF_TO_ORIGIN` should be specified if the user should be dropped off at the airport the flight is flying from – using the flight details provided.

`DeeplinkDirection.PICKUP_FROM_DESTINATION` should be specified if the user should be picked up at the airport the flight is flying to – using the flight details provided.

Same wording for iOS

2021-07-22 08:06 UTC, humphriest commented on Android.md
> +`<direction>` is an **enum** with the values of either `DeeplinkDirection.DROPOFF_TO_ORIGIN` or `DeeplinkDirection.PICKUP_FROM_DESTINATION`. `DeeplinkDirection.DROPOFF_TO_ORIGIN` is used when the use
I don't like the wording of this ` when the user on the transport (taxi, etc.)` but I see what you mean.
Maybe something like:
`DeeplinkDirection.DROPOFF_TO_ORIGIN` is used when the user needs a ride to the airport they are flying out of, using the flight details provided.
or
`DeeplinkDirection.DROPOFF_TO_ORIGIN` is used when the user is to be dropped off, by taxi or other, at the airport they are flying out of, using the flight details provided.

2021-07-22 10:40 UTC, gianpaj commented on Android.md
> +`<direction>` is an **enum** with the values of either `DeeplinkDirection.DROPOFF_TO_ORIGIN` or `DeeplinkDirection.PICKUP_FROM_DESTINATION`. `DeeplinkDirection.DROPOFF_TO_ORIGIN` is used when the use
ok, yes. those look good to me

2021-07-22 10:57 UTC, humphriest commented on Android.md
> +`<direction>` is an **enum** with the values of either `DeeplinkDirection.DROPOFF_TO_ORIGIN` or `DeeplinkDirection.PICKUP_FROM_DESTINATION`. `DeeplinkDirection.DROPOFF_TO_ORIGIN` is used when the use
Updated

2021-07-22 10:57 UTC, merged